### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by opkiler22789** [rwaldron/tessel-io#18]
Error:
```
>> /tmp/remote-script/node_modules/tessel-io/lib/index.js:842
      state.i2c[address].send(buffer);
                        ^

TypeError: Cannot read property 'send' of undefined
    at Board.i2cWrite (/tmp/remote-script/node_modules/tessel-io/lib/index.js:842:25)
    at t._transfer (/tmp/remote-script/node_modules/oled-js/oled.js:1:2777)
    at t._initialise (/tmp/remote-script/node_modules/oled-js/oled.js:1:2133)
    at new t (/tmp/remote-script/node_modules/oled-js/oled.js:1:1652)
    at t.<anonymous> (/tmp/remote-script/index.js:1:226)
    at emitNone (events.js:72:20)
    at t.emit (events.js:166:7)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

Code: 
```
var five = require('johnny-five'),
    Oled = require('oled-js');
var Tessel = require("tessel-io");
var board = new five.Board({
  io: new Tessel()
});
board.on('ready', function() {
  

  var opts = {
    width: 128,
    height: 32,
    address: 0x06
  };

  var oled = new Oled(board, five, opts);
  var font = require('oled-font-5x7');


oled.drawCircle(30, 10, 5, 1);
oled.update();

});
```

Hello, please tell me how to solve this problem

**Comment by rwaldron** [comment]
Thanks for the report! It's likely that `Oled-js` doesn't support passing through `opts` to io-plugins. Please file a bug here:  https://github.com/noopkat/oled-js/issues

**Comment by opkiler22789** [comment]
@rwaldron Thanks a similar alternative to the library there?

**Comment by rwaldron** [comment]
@opkiler22789 Why not file an issue and work with @noopkat to get the issue fixed? That seems like the best option to me.

**Comment by rwaldron** [comment]
Filed: https://github.com/noopkat/oled-js/issues/123
