### ISSUE TITLE
USB Barcode Scanner Serial Port

### ISSUE THREAD

**Issue by an-rahulpandey** [rwaldron/tessel-io#19]
Hi,

I have connected usb barcode scanner to my Tessel 2 board (Johnny-Five Kit) . Now I have read that I need to use serial port to communicate with scanner, but I am getting following run when running the program.

```
INFO Looking for your Tessel...
INFO Connected to InGen.
INFO Building project.
INFO Writing project to RAM on InGen (784.896 kB)...
INFO Deployed.
INFO Running barcodescanner.js...
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at dirname (path.js:1324:5)
    at Function.exports.getRoot.r [as getRoot] (/tmp/remote-script/node_modules/bindings/bindings.js:1:1659)
    at exports (/tmp/remote-script/node_modules/bindings/bindings.js:1:879)
    at Object.<anonymous> (/tmp/remote-script/node_modules/serialport/lib/bindings/linux.js:1:103)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
My barcodescanner.js file is - 

```
var five = require("johnny-five");
var Tessel = require("tessel-io");
var SerialPort = require("serialport").SerialPort;


var board = new five.Board({
    io: new Tessel()
});


// list serial ports:
SerialPort.list(function (err, ports) {
    ports.forEach(function (port) {
        console.log(port.comName);
    });
});

```

Please let me know what I am doing wrong here.

**Comment by rwaldron** [comment]
This is caused by a bug in the current version of node-serialport. It was fixed, but no release yet.

**Comment by joshunger** [comment]
@rwaldron any update and do you have a link to the issue in `node-serialport`? Thanks.

**Comment by an-rahulpandey** [comment]
@joshunger I am not sure if this help, but I got it working with some tweaks. However it was long back, don't know whether it still works or not - 

https://forums.tessel.io/t/serial-port-not-working/3271/30

**Comment by joshunger** [comment]
@an-rahulpandey thank you. It looks like `--full` fixes the issue. I couldn't find a big benefit using `node-serialport` over the tessel `UART` so I removed `node-serialport` for now.

**Comment by HipsterBrown** [comment]
@joshunger @an-rahulpandey So I think I've figured it out without using `--full`. Setting `--compress=false` when running `t2 run` or `t2 push` resolves the path error. Something about the uglify step is messing with the `bindings` package as used by `serialport`. 

I'm looking into why the compression it causing errors, but I think using the `--compress=false` setting is a good compromise in the meantime.

**Comment by joshunger** [comment]
Thanks! @HipsterBrown wasn't this fixed a year ago? https://github.com/tessel/t2-cli/pull/1279? Regression?

**Comment by HipsterBrown** [comment]
@joshunger Good spot. It looks like we introduced a regression when upgrading to uglify-js 3 (https://github.com/tessel/t2-cli/pull/1348). I'll need to verify that `base64id` still works without being on the blacklist.
