### ISSUE TITLE
Error when trying to use module- pwmFrequency not a function

### ISSUE THREAD

**Issue by d1runberg** [rwaldron/tessel-io#3]
When trying to use the tessel-io module I got this error report, even when not trying to use PWM. 

`/tmp/remote-script/node_modules/tessel-io/lib/tessel.js:445
        tessel.pwmFrequency(PWM_FREQUENCY);
               ^

TypeError: tessel.pwmFrequency is not a function
    at Tessel.options.pins.Tessel.pwmWrite (/tmp/remote-script/node_modules/tessel-io/lib/tessel.js:445:16)
    at t.r.DEFAULT.write.value (/tmp/remote-script/node_modules/johnny-five/lib/led/led.js:1:2098)
    at t.off (/tmp/remote-script/node_modules/johnny-five/lib/led/led.js:1:2431)
    at s.<anonymous> (/tmp/remote-script/index.js:1:530)
    at emitOne (events.js:77:13)
    at s.emit (events.js:169:7)
    at s.<anonymous> (/tmp/remote-script/node_modules/johnny-five/lib/keypad.js:1:1809)
    at Array.forEach (native)
    at s.d (/tmp/remote-script/node_modules/johnny-five/lib/keypad.js:1:1784)
    at s.<anonymous> (/tmp/remote-script/node_modules/johnny-five/lib/keypad.js:1:1278)`

**Comment by d1runberg** [comment]
Everything works when backing up a version

**Comment by rwaldron** [comment]
well, that's because t2-firmware hasn't been released yet and I totally published this to npm too soon. 

Whoops.

I'll roll back the PWM stuff tomorrow morning and get it published to unblock you. Sorry about that, but seriously it's worthy of a good laugh ;)

**Comment by d1runberg** [comment]
I figured!...dont worry about rolling back on my account! I put a sticky on
my monitor to manual spec previous version.




Derek Runberg
Regional Education Developer
Sparkfun Electronics Inc.

Boulder, CO.
Cell: 971-344-2355
derek.runberg@sparkfun.com
http://www.sparkfun.com
http://learn.sparkfun.com

**Comment by rwaldron** [comment]
Ah! That's a good fix for the time being—previous release and current only
differ in the PWM stuff
